name = "possiblygeek"
license = "SimPL-2.0"
licenselink = "https://github.com/delputnam/hugo-theme-delputnam/LICENSE.md"
description = ""
homepage = "https://github.com/delputnam/hugo-theme-delputnam"
tags = ["", ""]
features = ["", ""]

[author]
  name = "Del Putnam"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
